export const COUNTRY_DATA = [
  // Asia-Pacific
  { name: "Indonesia", code: "ID", flag: "🇮🇩", phoneCode: "+62", region: "Asia" },
  { name: "Malaysia", code: "MY", flag: "🇲🇾", phoneCode: "+60", region: "Asia" },
  { name: "Singapura", code: "SG", flag: "🇸🇬", phoneCode: "+65", region: "Asia" },
  { name: "Thailand", code: "TH", flag: "🇹🇭", phoneCode: "+66", region: "Asia" },
  { name: "Vietnam", code: "VN", flag: "🇻🇳", phoneCode: "+84", region: "Asia" },
  { name: "Filipina", code: "PH", flag: "🇵🇭", phoneCode: "+63", region: "Asia" },
  { name: "Kamboja", code: "KH", flag: "🇰🇭", phoneCode: "+855", region: "Asia" },
  { name: "Myanmar", code: "MM", flag: "🇲🇲", phoneCode: "+95", region: "Asia" },
  { name: "Laos", code: "LA", flag: "🇱🇦", phoneCode: "+856", region: "Asia" },
  { name: "Bangladesh", code: "BD", flag: "🇧🇩", phoneCode: "+880", region: "Asia" },
  { name: "India", code: "IN", flag: "🇮🇳", phoneCode: "+91", region: "Asia" },
  { name: "Pakistan", code: "PK", flag: "🇵🇰", phoneCode: "+92", region: "Asia" },
  { name: "Sri Lanka", code: "LK", flag: "🇱🇰", phoneCode: "+94", region: "Asia" },
  { name: "Nepal", code: "NP", flag: "🇳🇵", phoneCode: "+977", region: "Asia" },
  { name: "Bhutan", code: "BT", flag: "🇧🇹", phoneCode: "+975", region: "Asia" },
  { name: "Maldives", code: "MV", flag: "🇲🇻", phoneCode: "+960", region: "Asia" },
  { name: "Hong Kong", code: "HK", flag: "🇭🇰", phoneCode: "+852", region: "Asia" },
  { name: "Taiwan", code: "TW", flag: "🇹🇼", phoneCode: "+886", region: "Asia" },
  { name: "Macau", code: "MO", flag: "🇲🇴", phoneCode: "+853", region: "Asia" },
  { name: "Korea Selatan", code: "KR", flag: "🇰🇷", phoneCode: "+82", region: "Asia" },
  { name: "Korea Utara", code: "KP", flag: "🇰🇵", phoneCode: "+850", region: "Asia" },
  { name: "Jepang", code: "JP", flag: "🇯🇵", phoneCode: "+81", region: "Asia" },
  { name: "Mongol", code: "MN", flag: "🇲🇳", phoneCode: "+976", region: "Asia" },
  { name: "China", code: "CN", flag: "🇨🇳", phoneCode: "+86", region: "Asia" },
  { name: "Hong Kong", code: "HK", flag: "🇭🇰", phoneCode: "+852", region: "Asia" },

  // Middle East
  { name: "Arab Saudi", code: "SA", flag: "🇸🇦", phoneCode: "+966", region: "Middle East" },
  { name: "Uni Emirat Arab", code: "AE", flag: "🇦🇪", phoneCode: "+971", region: "Middle East" },
  { name: "Kuwait", code: "KW", flag: "🇰🇼", phoneCode: "+965", region: "Middle East" },
  { name: "Qatar", code: "QA", flag: "🇶🇦", phoneCode: "+974", region: "Middle East" },
  { name: "Bahrain", code: "BH", flag: "🇧🇭", phoneCode: "+973", region: "Middle East" },
  { name: "Oman", code: "OM", flag: "🇴🇲", phoneCode: "+968", region: "Middle East" },
  { name: "Yaman", code: "YE", flag: "🇾🇪", phoneCode: "+967", region: "Middle East" },
  { name: "Israel", code: "IL", flag: "🇮🇱", phoneCode: "+972", region: "Middle East" },
  { name: "Palestina", code: "PS", flag: "🇵🇸", phoneCode: "+970", region: "Middle East" },
  { name: "Yordania", code: "JO", flag: "🇯🇴", phoneCode: "+962", region: "Middle East" },
  { name: "Libanon", code: "LB", flag: "🇱🇧", phoneCode: "+961", region: "Middle East" },
  { name: "Suriah", code: "SY", flag: "🇸🇾", phoneCode: "+963", region: "Middle East" },
  { name: "Irak", code: "IQ", flag: "🇮🇶", phoneCode: "+964", region: "Middle East" },
  { name: "Iran", code: "IR", flag: "🇮🇷", phoneCode: "+98", region: "Middle East" },
  { name: "Turki", code: "TR", flag: "🇹🇷", phoneCode: "+90", region: "Middle East" },
  { name: "Mesir", code: "EG", flag: "🇪🇬", phoneCode: "+20", region: "Africa" },

  // Europe
  { name: "Inggris", code: "GB", flag: "🇬🇧", phoneCode: "+44", region: "Europe" },
  { name: "Prancis", code: "FR", flag: "🇫🇷", phoneCode: "+33", region: "Europe" },
  { name: "Jerman", code: "DE", flag: "🇩🇪", phoneCode: "+49", region: "Europe" },
  { name: "Spanyol", code: "ES", flag: "🇪🇸", phoneCode: "+34", region: "Europe" },
  { name: "Italia", code: "IT", flag: "🇮🇹", phoneCode: "+39", region: "Europe" },
  { name: "Belanda", code: "NL", flag: "🇳🇱", phoneCode: "+31", region: "Europe" },
  { name: "Belgum", code: "BE", flag: "🇧🇪", phoneCode: "+32", region: "Europe" },
  { name: "Polandia", code: "PL", flag: "🇵🇱", phoneCode: "+48", region: "Europe" },
  { name: "Rusia", code: "RU", flag: "🇷🇺", phoneCode: "+7", region: "Europe" },
  { name: "Ukraina", code: "UA", flag: "🇺🇦", phoneCode: "+380", region: "Europe" },
  { name: "Romania", code: "RO", flag: "🇷🇴", phoneCode: "+40", region: "Europe" },
  { name: "Bulgaria", code: "BG", flag: "🇧🇬", phoneCode: "+359", region: "Europe" },
  { name: "Hungaria", code: "HU", flag: "🇭🇺", phoneCode: "+36", region: "Europe" },
  { name: "Ceko", code: "CZ", flag: "🇨🇿", phoneCode: "+420", region: "Europe" },
  { name: "Slowakia", code: "SK", flag: "🇸🇰", phoneCode: "+421", region: "Europe" },
  { name: "Slovenia", code: "SI", flag: "🇸🇮", phoneCode: "+386", region: "Europe" },
  { name: "Kroasia", code: "HR", flag: "🇭🇷", phoneCode: "+385", region: "Europe" },
  { name: "Serbia", code: "RS", flag: "🇷🇸", phoneCode: "+381", region: "Europe" },
  { name: "Bosnia", code: "BA", flag: "🇧🇦", phoneCode: "+387", region: "Europe" },
  { name: "Montenegro", code: "ME", flag: "🇲🇪", phoneCode: "+382", region: "Europe" },
  { name: "Makedonia", code: "MK", flag: "🇲🇰", phoneCode: "+389", region: "Europe" },
  { name: "Albania", code: "AL", flag: "🇦🇱", phoneCode: "+355", region: "Europe" },
  { name: "Yunani", code: "GR", flag: "🇬🇷", phoneCode: "+30", region: "Europe" },
  { name: "Portugal", code: "PT", flag: "🇵🇹", phoneCode: "+351", region: "Europe" },
  { name: "Austria", code: "AT", flag: "🇦🇹", phoneCode: "+43", region: "Europe" },
  { name: "Swiss", code: "CH", flag: "🇨🇭", phoneCode: "+41", region: "Europe" },
  { name: "Swedia", code: "SE", flag: "🇸🇪", phoneCode: "+46", region: "Europe" },
  { name: "Norwegia", code: "NO", flag: "🇳🇴", phoneCode: "+47", region: "Europe" },
  { name: "Finlandia", code: "FI", flag: "🇫🇮", phoneCode: "+358", region: "Europe" },
  { name: "Denmark", code: "DK", flag: "🇩🇰", phoneCode: "+45", region: "Europe" },
  { name: "Islandia", code: "IS", flag: "🇮🇸", phoneCode: "+354", region: "Europe" },
  { name: "Irlandia", code: "IE", flag: "🇮🇪", phoneCode: "+353", region: "Europe" },
  { name: "Luksemburg", code: "LU", flag: "🇱🇺", phoneCode: "+352", region: "Europe" },
  { name: "Malta", code: "MT", flag: "🇲🇹", phoneCode: "+356", region: "Europe" },
  { name: "Siprus", code: "CY", flag: "🇨🇾", phoneCode: "+357", region: "Europe" },

  // Americas
  { name: "Amerika Serikat", code: "US", flag: "🇺🇸", phoneCode: "+1", region: "Americas" },
  { name: "Kanada", code: "CA", flag: "🇨🇦", phoneCode: "+1", region: "Americas" },
  { name: "Meksiko", code: "MX", flag: "🇲🇽", phoneCode: "+52", region: "Americas" },
  { name: "Brazil", code: "BR", flag: "🇧🇷", phoneCode: "+55", region: "Americas" },
  { name: "Argentina", code: "AR", flag: "🇦🇷", phoneCode: "+54", region: "Americas" },
  { name: "Chili", code: "CL", flag: "🇨🇱", phoneCode: "+56", region: "Americas" },
  { name: "Peru", code: "PE", flag: "🇵🇪", phoneCode: "+51", region: "Americas" },
  { name: "Kolombia", code: "CO", flag: "🇨🇴", phoneCode: "+57", region: "Americas" },
  { name: "Venezuela", code: "VE", flag: "🇻🇪", phoneCode: "+58", region: "Americas" },
  { name: "Ekuador", code: "EC", flag: "🇪🇨", phoneCode: "+593", region: "Americas" },
  { name: "Bolivia", code: "BO", flag: "🇧🇴", phoneCode: "+591", region: "Americas" },
  { name: "Paraguay", code: "PY", flag: "🇵🇾", phoneCode: "+595", region: "Americas" },
  { name: "Uruguay", code: "UY", flag: "🇺🇾", phoneCode: "+598", region: "Americas" },
  { name: "Guyana", code: "GY", flag: "🇬🇾", phoneCode: "+592", region: "Americas" },
  { name: "Surinam", code: "SR", flag: "🇸🇷", phoneCode: "+597", region: "Americas" },
  { name: "Costa Rica", code: "CR", flag: "🇨🇷", phoneCode: "+506", region: "Americas" },
  { name: "Panama", code: "PA", flag: "🇵🇦", phoneCode: "+507", region: "Americas" },
  { name: "Nikaragua", code: "NI", flag: "🇳🇮", phoneCode: "+505", region: "Americas" },
  { name: "Honduras", code: "HN", flag: "🇭🇳", phoneCode: "+504", region: "Americas" },
  { name: "El Salvador", code: "SV", flag: "🇸🇻", phoneCode: "+503", region: "Americas" },
  { name: "Guatemala", code: "GT", flag: "🇬🇹", phoneCode: "+502", region: "Americas" },
  { name: "Belize", code: "BZ", flag: "🇧🇿", phoneCode: "+501", region: "Americas" },
  { name: "Jamaika", code: "JM", flag: "🇯🇲", phoneCode: "+1", region: "Americas" },
  { name: "Trinidad Tobago", code: "TT", flag: "🇹🇹", phoneCode: "+1", region: "Americas" },
  { name: "Kuba", code: "CU", flag: "🇨🇺", phoneCode: "+53", region: "Americas" },
  { name: "Dominican Rep", code: "DO", flag: "🇩🇴", phoneCode: "+1", region: "Americas" },
  { name: "Puerto Rico", code: "PR", flag: "🇵🇷", phoneCode: "+1", region: "Americas" },

  // Africa
  { name: "Afrika Selatan", code: "ZA", flag: "🇿🇦", phoneCode: "+27", region: "Africa" },
  { name: "Nigeria", code: "NG", flag: "🇳🇬", phoneCode: "+234", region: "Africa" },
  { name: "Kenya", code: "KE", flag: "🇰🇪", phoneCode: "+254", region: "Africa" },
  { name: "Tanzania", code: "TZ", flag: "🇹🇿", phoneCode: "+255", region: "Africa" },
  { name: "Uganda", code: "UG", flag: "🇺🇬", phoneCode: "+256", region: "Africa" },
  { name: "Ethiopia", code: "ET", flag: "🇪🇹", phoneCode: "+251", region: "Africa" },
  { name: "Ghana", code: "GH", flag: "🇬🇭", phoneCode: "+233", region: "Africa" },
  { name: "Senegal", code: "SN", flag: "🇸🇳", phoneCode: "+221", region: "Africa" },
  { name: "Pantai Gading", code: "CI", flag: "🇨🇮", phoneCode: "+225", region: "Africa" },
  { name: "Mali", code: "ML", flag: "🇲🇱", phoneCode: "+223", region: "Africa" },
  { name: "Burkina Faso", code: "BF", flag: "🇧🇫", phoneCode: "+226", region: "Africa" },
  { name: "Niger", code: "NE", flag: "🇳🇪", phoneCode: "+227", region: "Africa" },
  { name: "Chad", code: "TD", flag: "🇹🇩", phoneCode: "+235", region: "Africa" },
  { name: "Cameroon", code: "CM", flag: "🇨🇲", phoneCode: "+237", region: "Africa" },
  { name: "Gabon", code: "GA", flag: "🇬🇦", phoneCode: "+241", region: "Africa" },
  { name: "Kongo", code: "CG", flag: "🇨🇬", phoneCode: "+242", region: "Africa" },
  { name: "DR Kongo", code: "CD", flag: "🇨🇩", phoneCode: "+243", region: "Africa" },
  { name: "Angola", code: "AO", flag: "🇦🇴", phoneCode: "+244", region: "Africa" },
  { name: "Zambia", code: "ZM", flag: "🇿🇲", phoneCode: "+260", region: "Africa" },
  { name: "Zimbabwe", code: "ZW", flag: "🇿🇼", phoneCode: "+263", region: "Africa" },
  { name: "Malawi", code: "MW", flag: "🇲🇼", phoneCode: "+265", region: "Africa" },
  { name: "Mozambik", code: "MZ", flag: "🇲🇿", phoneCode: "+258", region: "Africa" },
  { name: "Madagascar", code: "MG", flag: "🇲🇬", phoneCode: "+261", region: "Africa" },
  { name: "Mauritius", code: "MU", flag: "🇲🇺", phoneCode: "+230", region: "Africa" },
  { name: "Seychelles", code: "SC", flag: "🇸🇨", phoneCode: "+248", region: "Africa" },
  { name: "Sudan", code: "SD", flag: "🇸🇩", phoneCode: "+249", region: "Africa" },
  { name: "Somalia", code: "SO", flag: "🇸🇴", phoneCode: "+252", region: "Africa" },
  { name: "Djibouti", code: "DJ", flag: "🇩🇯", phoneCode: "+253", region: "Africa" },
  { name: "Eritrea", code: "ER", flag: "🇪🇷", phoneCode: "+291", region: "Africa" },
  { name: "Togo", code: "TG", flag: "🇹🇬", phoneCode: "+228", region: "Africa" },
  { name: "Benin", code: "BJ", flag: "🇧🇯", phoneCode: "+229", region: "Africa" },
  { name: "Liberia", code: "LR", flag: "🇱🇷", phoneCode: "+231", region: "Africa" },
  { name: "Sierra Leone", code: "SL", flag: "🇸🇱", phoneCode: "+232", region: "Africa" },
  { name: "Guinea", code: "GN", flag: "🇬🇳", phoneCode: "+224", region: "Africa" },
  { name: "Guinea-Bissau", code: "GW", flag: "🇬🇼", phoneCode: "+245", region: "Africa" },
  { name: "Mauritania", code: "MR", flag: "🇲🇷", phoneCode: "+222", region: "Africa" },
  { name: "Morocco", code: "MA", flag: "🇲🇦", phoneCode: "+212", region: "Africa" },
  { name: "Algeria", code: "DZ", flag: "🇩🇿", phoneCode: "+213", region: "Africa" },
  { name: "Tunisia", code: "TN", flag: "🇹🇳", phoneCode: "+216", region: "Africa" },
  { name: "Libya", code: "LY", flag: "🇱🇾", phoneCode: "+218", region: "Africa" },

  // Oceania
  { name: "Australia", code: "AU", flag: "🇦🇺", phoneCode: "+61", region: "Oceania" },
  { name: "Selandia Baru", code: "NZ", flag: "🇳🇿", phoneCode: "+64", region: "Oceania" },
  { name: "Fiji", code: "FJ", flag: "🇫🇯", phoneCode: "+679", region: "Oceania" },
  { name: "Papua Nugini", code: "PG", flag: "🇵🇬", phoneCode: "+675", region: "Oceania" },
  { name: "Solomon Islands", code: "SB", flag: "🇸🇧", phoneCode: "+677", region: "Oceania" },
  { name: "Samoa", code: "WS", flag: "🇼🇸", phoneCode: "+685", region: "Oceania" },
  { name: "Vanuatu", code: "VU", flag: "🇻🇺", phoneCode: "+678", region: "Oceania" },
  { name: "Kiribati", code: "KI", flag: "🇰🇮", phoneCode: "+686", region: "Oceania" },
  { name: "Nauru", code: "NR", flag: "🇳🇷", phoneCode: "+674", region: "Oceania" },
  { name: "Tonga", code: "TO", flag: "🇹🇴", phoneCode: "+676", region: "Oceania" },
  { name: "Palau", code: "PW", flag: "🇵🇼", phoneCode: "+680", region: "Oceania" },
  { name: "Marshall Islands", code: "MH", flag: "🇲🇭", phoneCode: "+692", region: "Oceania" },
  { name: "Mikronesia", code: "FM", flag: "🇫🇲", phoneCode: "+691", region: "Oceania" },
]

export type CountryType = (typeof COUNTRY_DATA)[0]
