// ... existing imports ...
import "./globals.css"
import type { Metadata } from "next"

export const metadata: Metadata = {
  metadataBase: new URL("https://katsumibotv6.vestia.icu"),
  title: {
    default: "Katsumi Bot - WhatsApp Telegram Bot Gratis Indonesia 2025 | Download Media | Katsumi MD",
    template: "%s | Katsumi Bot",
  },
  description:
    "Katsumi Bot adalah bot WhatsApp dan Telegram multifungsi gratis terbaik Indonesia 2025. Fitur AI chat, downloader TikTok/YouTube/Instagram, sticker maker, auto reply, reminder, games, translator, dan 500+ command. Katsumi MD Bot terbaik untuk automation messaging. Mudah digunakan tanpa coding, aman terenkripsi, dan didukung 200+ negara!",
  keywords: [
    "katsumi bot",
    "katsumi",
    "katsumi md",
    "md katsumi",
    "whatsapp bot",
    "telegram bot",
    "bot gratis",
    "bot indonesia",
    "whatsapp bot gratis",
    "telegram bot gratis",
    "best whatsapp bot",
    "best telegram bot",
    "katsumi whatsapp",
    "katsumi telegram",
    "katsumi ai",
    "katsumi auto reply",
    "katsumi downloader",
    "katsumi sticker maker",
    "katsumi bot indonesia",
    "katsumi bot gratis",
    "md bot whatsapp",
    "md bot telegram",
    "katsumi bot 2025",
    "katsumi latest version",
    "katsumi bot features",
    "katsumi bot commands",
    "whatsapp assistant",
    "telegram assistant",
    "ai bot",
    "ai chat bot",
    "chatbot whatsapp",
    "chatbot telegram",
    "automated bot",
    "messaging bot",
    "download bot",
    "downloader",
    "tiktok downloader",
    "youtube downloader",
    "instagram downloader",
    "facebook downloader",
    "media downloader",
    "video downloader",
    "audio downloader",
    "music downloader",
    "sticker maker",
    "sticker bot",
    "emoji bot",
    "image to sticker",
    "custom sticker",
    "sticker converter",
    "auto reply bot",
    "autoresponder",
    "message automation",
    "reminder bot",
    "scheduler bot",
    "alarm bot",
    "notification bot",
    "alert system",
    "weather bot",
    "weather assistant",
    "news bot",
    "news reader",
    "translator bot",
    "language translator",
    "translate messages",
    "calculator bot",
    "math calculator",
    "unit converter",
    "currency converter",
    "dictionary bot",
    "vocabulary bot",
    "joke bot",
    "meme bot",
    "quotes bot",
    "lyrics bot",
    "song lyrics",
    "tarot bot",
    "zodiac bot",
    "horoscope bot",
    "astrology bot",
    "game bot",
    "mini games",
    "quiz bot",
    "trivia bot",
    "fitness bot",
    "health bot",
    "diet bot",
    "workout bot",
    "calorie tracker",
    "meditation bot",
    "journal bot",
    "todo bot",
    "task manager",
    "productivity bot",
    "time tracker",
    "study bot",
    "learning bot",
    "education bot",
    "tutor bot",
    "content writer bot",
    "article bot",
    "story bot",
    "poem bot",
    "creative bot",
    "art bot",
    "design bot",
    "photo editor bot",
    "image editor",
    "qr code generator",
    "pdf converter",
    "file converter",
    "compression bot",
    "social media bot",
    "facebook bot",
    "instagram bot",
    "twitter bot",
    "youtube bot",
    "tiktok automation",
    "instagram automation",
    "facebook automation",
    "content scheduler",
    "post scheduler",
    "engagement bot",
    "follower tracker",
    "analytics bot",
    "seo analyzer",
    "website checker",
    "security bot",
    "vpn bot",
    "proxy bot",
    "password manager",
    "encryption bot",
    "coding bot",
    "programming bot",
    "api bot",
    "webhook bot",
    "automation script",
    "batch processor",
    "data processor",
    "webhook handler",
    "event listener",
    "katsumi documentation",
    "katsumi tutorial",
    "katsumi guide",
    "katsumi setup",
    "katsumi installation",
    "how to use katsumi",
    "katsumi tips tricks",
    "katsumi features list",
    "katsumi command list",
    "katsumi error fix",
    "katsumi troubleshooting",
    "katsumi faq",
    "katsumi help support",
  ],
  openGraph: {
    type: "website",
    locale: "id_ID",
    url: "https://katsumibotv6.vestia.icu",
    siteName: "Katsumi Bot - Katsumi MD WhatsApp Telegram Bot",
    title: "Katsumi Bot - Bot WhatsApp Telegram Gratis Indonesia 2025",
    description:
      "Katsumi Bot - Bot WhatsApp & Telegram multifungsi gratis dengan 500+ fitur. Katsumi MD terbaik untuk automation. Download TikTok, YouTube, Instagram. Sticker maker, AI chat, auto reply, dan banyak lagi!",
    images: [
      {
        url: "https://files.catbox.moe/atbxcg.png",
        width: 512,
        height: 512,
        alt: "Katsumi Bot Logo",
        type: "image/png",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Katsumi Bot - Bot WhatsApp Telegram Gratis Indonesia",
    description:
      "Katsumi Bot adalah bot WhatsApp & Telegram terbaik dengan 500+ fitur gratis. Katsumi MD automation bot terdepan.",
    images: ["https://files.catbox.moe/atbxcg.png"],
    creator: "@katsumibot",
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  alternates: {
    canonical: "https://katsumibotv6.vestia.icu",
    languages: {
      "id-ID": "https://katsumibotv6.vestia.icu",
      "en-US": "https://katsumibotv6.vestia.icu/en",
    },
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
